Final Surge stage 6
DenisShixtich1984/FinalSurge pull request #1
Opened 2022-07-16 11:15 UTC by DenisShixtich1984

sketch of the first tests in the diploma

2022-07-19 09:52 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/tests/CalculatorsTest.java
> +    /**
если добавляешь коменты к классы делай их перед классом, тоже самое и методов над методом коменты

2022-07-19 09:53 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/steps/CalculatorsSteps.java
> +
посмотри отступы, пустые строки везде в коде

2022-07-19 09:53 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/steps/CalculatorsSteps.java
> +    }
отступ

2022-07-19 09:53 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/steps/CalculatorsSteps.java
> +
отступ

2022-07-19 09:54 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/steps/OtherCalculatorsSteps.java
> +        reader = new PropertyReader();
повторяется в каждой странице, вынеси в бейс пейджу

2022-07-19 09:54 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/steps/OtherCalculatorsSteps.java
> +    @Step
пустая строка должна быть

2022-07-19 09:55 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/pages/LoginPage.java
> +    PropertyReader reader = new PropertyReader();
проперти ридер в каждой странице, сделалай бейс пейджу

2022-07-19 09:56 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/pages/SettingsPage.java
> +    public SelenideElement checkCounty = $x("/html/body/div[1]/div[3]/div/div[1]/div[1]/div[2]/div/div[2]/p[6]");
ужаснейщий локатор нужно менять

2022-07-19 09:58 UTC, VladimirVolkovD commented on src/test/java/com/finalsurge/pages/SettingsPage.java
> +    public SelenideElement buttonSettings = $x("//a[text()='Settings']");
По тексту так себе, может получше способ есть, для поиска по тексту лучше уже $(byText("Settings")

2022-07-19 10:03 UTC, VladimirVolkovD requested changes

2022-07-19 10:03 UTC, VladimirVolkovVD commented on src/test/java/com/finalsurge/pages/SettingsPage.java
> +    public SelenideElement errorMessageWrongSymbol = $x("//*[@class='alert alert-error']");
$(By.className(

2022-07-19 10:03 UTC, VladimirVolkovVD commented on src/test/java/com/finalsurge/pages/SettingsPage.java
> +//        buttonChangeAvatar.click();
если что-то закоменчено значит лидо его нужно доделать, либо это мусор и тогда удалить

2022-07-19 10:03 UTC, VladimirVolkovVD commented on src/test/java/com/finalsurge/browser/SelenideConfiguration.java
>          Configuration.browserSize = "1000x1000";
если уже начал запихивать параметры в проперти то пихай уже все

2022-07-19 10:03 UTC, VladimirVolkovVD commented on src/test/java/com/finalsurge/pages/CalculatorsPage.java
> +    public SelenideElement messageNumberAfterEnterDate = $x("//*[@id='intensity-calc']/div/div[3]/div[2]/table/tbody/tr[2]/td[4]");
тоже чет страшный локатор

2022-08-01 12:52 UTC, VladimirVolkovD approved these changes

2022-08-03 07:39 UTC, merged